package com.gitlab.utils;

import com.gitlab.models.Issue;
import com.gitlab.restClients.IssuesRestClient;
import io.qameta.allure.Attachment;
import lombok.Data;
import org.testng.annotations.AfterSuite;


import java.util.Arrays;
import java.util.List;

@Data
public abstract class BaseTest {

    @Attachment
    public static String attachedInfo(String string) {
        return string;
    }

    /**
     * Cleanup. Delete all generated by the tests issues.
     */
    @AfterSuite
    public void afterSuite() {
        List<Issue> issueList = Arrays.asList(IssuesRestClient.getAllIssues());
        issueList.forEach(issue -> IssuesRestClient.deleteIssue((Integer) issue.getIid()));
    }
}